/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'background': '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'error-container': '#ffdad6',
        'secondary-fixed': '#c9e6ff',
        'surface-tint': '#4d44e3',
        'error': '#ba1a1a',
        'inverse-primary': '#c3c0ff',
        'tertiary': '#7e3000',
        'on-surface': '#0b1c30',
        'surface-container': '#e5eeff',
        'on-tertiary-fixed-variant': '#7b2f00',
        'on-tertiary-container': '#ffd2be',
        'surface-container-lowest': '#ffffff',
        'inverse-on-surface': '#eaf1ff',
        'on-secondary': '#ffffff',
        'surface-bright': '#f8f9ff',
        'on-primary-fixed': '#0f0069',
        'surface-container-highest': '#d3e4fe',
        'inverse-surface': '#213145',
        'on-secondary-container': '#004666',
        'on-primary-container': '#dad7ff',
        'tertiary-fixed-dim': '#ffb695',
        'outline': '#777587',
        'tertiary-fixed': '#ffdbcc',
        'tertiary-container': '#a44100',
        'surface-variant': '#d3e4fe',
        'primary-container': '#4f46e5',
        'on-error-container': '#93000a',
        'surface-container-high': '#dce9ff',
        'on-secondary-fixed': '#001e2f',
        'secondary-fixed-dim': '#89ceff',
        'on-error': '#ffffff',
        'on-surface-variant': '#464555',
        'on-primary-fixed-variant': '#3323cc',
        'outline-variant': '#c7c4d8',
        'on-tertiary': '#ffffff',
        'surface': '#f8f9ff',
        'secondary-container': '#39b8fd',
        'primary-fixed': '#e2dfff',
        'on-primary': '#ffffff',
        'on-background': '#0b1c30',
        'primary-fixed-dim': '#c3c0ff',
        'on-tertiary-fixed': '#351000',
        'secondary': '#006591',
        'primary': '#3525cd',
        'surface-container-low': '#eff4ff',
        'on-secondary-fixed-variant': '#004c6e',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        'full': '9999px',
      },
      fontFamily: {
        'sans': ['Inter', 'system-ui', 'sans-serif'],
        'geist': ['Geist', 'sans-serif'],
      },
      boxShadow: {
        'ambient': '0 4px 6px -1px rgb(0 0 0 / 0.05), 0 2px 4px -2px rgb(0 0 0 / 0.05)',
        'ambient-lg': '0 10px 15px -3px rgb(0 0 0 / 0.07), 0 4px 6px -4px rgb(0 0 0 / 0.07)',
      },
    },
  },
  plugins: [],
}
